In [21]:
%load_ext autoreload
# reloads the file constantly so you don't need to reset
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
%reload_ext autoreload

In [2]:
# import the libraries
from cluster import (
    KMeans, 
    Silhouette, 
    make_clusters,
    plot_clusters,
    plot_multipanel)
import numpy as np
from scipy.spatial.distance import cdist

In [10]:
dir(plot_clusters)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [3]:
# read in an np array
mat,labels = make_clusters()
# kmeans
kmean = KMeans(k=2)
KMeans.fit(kmean, mat)

pred = kmean.predict(mat)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
kmean.centroids

array([[-9.74961184,  8.73300902],
       [ 1.90571667,  1.68018456]])

In [21]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2).fit(mat)
kmeans.predict(mat)
compare_centroids = KMeans(n_clusters=2)
kmeans.cluster_centers_  #cool, clusters are the same

array([[ 1.90571667,  1.68018456],
       [-9.74961184,  8.73300902]])

In [9]:
distances = cdist(mat, centroids, 'euclidean')
distances.shape
mat.shape
clusters = np.array([np.argmin(i) for i in distances])
#clusters

In [54]:
sse = 0
for point in range(distances.shape[0]):
    sse = sse + np.square(distances[point][clusters[point]])
    
sse

4905.820736532637

In [22]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2).fit(mat)
kmeans.predict(mat)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [57]:
# test silouette scores
score = Silhouette().score(X=mat, y=pred)

score

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [3]:
mat, labels = make_clusters(k=4, scale=1)

In [95]:
# get k random observations from the matrix as our starting centroids
centroids = mat[np.random.choice(clusters.shape[0], 4, replace = False)] # this is a np.array
# initialize iterations
iterations = 0
# initialize new_error and error change to a very large value
new_error = 10000
delta_loss = 1000

while iterations < 100 and delta_loss > 1e-6:
    distances = cdist(mat, centroids, 'euclidean')
    clusters = np.array([np.argmin(i) for i in distances])
    centroids = np.empty(centroids.shape)
    # for each label
    for i in range(4):
        centroids[i] = np.mean(mat[clusters == i], axis=0)
    sse = 0
    for point in range(distances.shape[0]):
        sse = sse + np.square(distances[point][clusters[point]])
    
    error = sse/distances.shape[0]
    delta_loss = np.abs(new_error - error)
    if new_error > error:
        break
    else:
        new_error = error
    iterations += 1
    
centroids

array([[-5.29167043, -0.5010371 ],
       [ 8.90376386,  3.92500241],
       [ 6.81594128, -4.17595472],
       [ 7.49425701, -2.46738379]])

In [90]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4).fit(mat)
kmeans.cluster_centers_


array([[ 8.90376386,  3.92500241],
       [-3.99311493, -2.32043301],
       [ 6.98552022, -3.74881199],
       [-6.54833704,  1.25966862]])

In [61]:
distances

array([[14.9741462 , 12.76381582,  1.96149942,  0.33358171],
       [14.79521847, 12.64431522,  2.14524809,  0.61772432],
       [15.890736  , 13.36966462,  1.45515712,  1.22756062],
       ...,
       [ 2.15563636,  2.13822606, 13.78932402, 14.57963171],
       [ 0.12588821,  3.91536504, 14.52194353, 15.08519925],
       [ 2.04180207,  4.52645329, 16.10201655, 16.80535062]])

In [55]:
distances = cdist(mat, centroids, 'euclidean')
clusters = np.array([np.argmin(i) for i in distances])
clusters

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,

In [ ]:
        for point in range(0, X.shape[0]):

            data_point = X[point]
            current_cluster = y[point]

            # indices for points in the same cluster
            this_cluster = np.where(y == current_cluster)[0]
            # indices for points in the other clusters
            other_cluster = np.where(y != current_cluster)[0]

            # calculate a
            a = []
            for other_point in this_cluster:
                # if its not the same point
                if point != other_point:
                    a.append(distances[point, other_point])
                    print(a)

            final_a = np.mean(a)

In [5]:
scores=[]
X = mat
y = labels
# Go through each data point index
for point in range(0, X.shape[0]):

    data_point = X[point]
    current_cluster = y[point]
    a = []

    # calculate a
    # indices for points in the same cluster
    this_cluster = np.where(y == current_cluster)[0]
            # for other points within the same cluster, go through the indices
            #for within_cluster_point in this_cluster:
                # calculate the distance between the current point and the points within the cluster
    for this_cluster_point in this_cluster:
        
        a.append(cdist(np.reshape(data_point, (-1, 2)), np.reshape(X[this_cluster_point], (-1, 2)), 'euclidean'))
        
    final_a = np.sum(a) / (len(this_cluster) - 1)

            # calculate b
            # initialize list
    final_b = []
            # for each possible classification label
    for label in range(max(y)):
        b = []
                # get other points that are not in the same cluster as the current point
        if label == current_cluster:
            continue
        else:
                    # for each other label, calculate distance between current point and other label, in a list b
            for other_cluster_point in np.where(y == label)[0]:
                b.append(float(cdist(np.reshape(data_point, (-1, 2)), np.reshape(X[other_cluster_point], (-1, 2)), 'euclidean')))
        final_b.append(np.average(b))

            # get the minimum of the average distance values for each label, this is the final b
    final_b = np.min(final_b)

    # calculate silhouette score
    # add score to the scores array
    scores.append((final_b - final_a) / max(final_a, final_b))
    
    scores

In [10]:
cdist(np.reshape(data_point, (-1, 2)), np.reshape(X[this_cluster_point], (-1, 2)), 'euclidean')

array([[0.]])

In [73]:
np.reshape(X[point], (-1, 2))

array([[7.13010175, 4.36107067]])

In [44]:
b = []
final_b = []
for label in range(max(np.unique(y))):
    if label != current_cluster:
        for other_cluster_point in np.where(y == label)[0]:
            #if other_cluster_point != data_point:
            b.append(cdist(np.reshape(data_point, (-1, 2)), np.reshape(X[other_cluster_point], (-1, 2)), 'euclidean'))
    final_b = np.mean(b)
        
final_b = min(b)

final_b

# for each label that's not the same as the label as the current point:
# claculate average distance to all the other points with each other label
# between the average distances for each other label, get the minimum as b

array([[1.96702606]])